version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
#  Disable while paths can't be ignored as it'd update all 'auto-approve-sync-files.yml', Renovate will handle exclusion
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
#  Disable for now, it doesn't handle well pnpm, Renovate handles it
#  - package-ecosystem: "npm"
#    directory: "/"
#    schedule:
#      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
